///TIME FRAME 1
use partygatetf1_040122to010822, clear
///regression no lead
regress FTSE100 Relevance
regress FTSEALL Relevance
///regression lead 1
regress FTSE100 Relevance_lead1
regress FTSEALL Relevance_lead1
///regression lead 2
regress FTSE100 Relevance_lead2
regress FTSEALL Relevance_lead2
///regression lead 3
regress FTSE100 Relevance_lead3
regress FTSEALL Relevance_lead3
///regression rolling avg
regress FTSE100 occurrences_rolling
regress FTSEALL occurrences_rolling

///TIME FRAME 2
use partygatetf2_030123to310323, clear
///regression no lead
regress FTSE100 Relevance
regress FTSEALL Relevance
///regression lead 1
regress FTSE100 Relevance_lead1
regress FTSEALL Relevance_lead1
///regression lead 2
regress FTSE100 Relevance_lead2
regress FTSEALL Relevance_lead2
///regression lead 3
regress FTSE100 Relevance_lead3
regress FTSEALL Relevance_lead3
///regression rolling avg
regress FTSE100 occurrences_rolling
regress FTSEALL occurrences_rolling


///TIME FRAME 3
use partygatetf3_020523to010823, clear
///regression no lead
regress FTSE100 Relevance
regress FTSEALL Relevance
///regression lead 1
regress FTSE100 Relevance_lead1
regress FTSEALL Relevance_lead1
///regression lead 2
regress FTSE100 Relevance_lead2
regress FTSEALL Relevance_lead2
///regression lead 3
regress FTSE100 Relevance_lead3
regress FTSEALL Relevance_lead3
///regression rolling avg
regress FTSE100 occurrences_rolling
regress FTSEALL occurrences_rolling

///TIME FRAME 4
use partygatetf4_140923to151123, clear
///regression no lead
regress FTSE100 Relevance
regress FTSEALL Relevance
///regression lead 1
regress FTSE100 Relevance_lead1
regress FTSEALL Relevance_lead1
///regression lead 2
regress FTSE100 Relevance_lead2
regress FTSEALL Relevance_lead2
///regression lead 3
regress FTSE100 Relevance_lead3
regress FTSEALL Relevance_lead3
///regression rolling avg
regress FTSE100 occurrences_rolling
regress FTSEALL occurrences_rolling